In [ ]:
#| default_exp data.netcdf

# NetCDF

> Convertion of MARIS data encoded as `.csv` to `.netCDF`.

In [ ]:
import pandas as pd
from netCDF4 import Dataset
#import xarray as xr

from pathlib import Path
import glob
import time

#from marisco.data.core import DumpExploder
#from marisco.data.serializer import flatten_cols

pd.set_option('display.max_rows', 500)
#%load_ext autoreload
#%autoreload 2

import warnings
warnings.filterwarnings('ignore')

## Converting a single file from `csv` to `netCDF`

In [ ]:
fname = Path('../_data/exploded/31-aarkrog-et-al-1992.csv')
df = pd.read_csv(fname)

In [ ]:
df.head()

,sample_id,area_id,areaname,samptype_id,samptype,ref_id,displaytext,zoterourl,ref_note,datbase,...,profile_id,sampnote,ref_fulltext,ref_yearpub,ref_sampleTypes,LongLat,displaycoordinates,DisplayLong,DisplayLat,id
0,2010,1912,North Atlantic Ocean,1,Seawater,31,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Table 4.3,NaN,...,NaN,NaN,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992,1,"-24.383,65.683",0xE6100000010CD656EC2FBB6B50408A8EE4F21F6238C0,-24.383333,65.683333,461829
1,2045,1912,North Atlantic Ocean,1,Seawater,31,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Table 4.3,NaN,...,NaN,NaN,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992,1,"-24.383,65.683",0xE6100000010CD656EC2FBB6B50408A8EE4F21F6238C0,-24.383333,65.683333,461830
2,2111,1912,North Atlantic Ocean,1,Seawater,31,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Table 4.3,NaN,...,NaN,NaN,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992,1,"-24.383,65.683",0xE6100000010CD656EC2FBB6B50408A8EE4F21F6238C0,-24.383333,65.683333,461831
3,2026,2356,Greenland Sea,1,Seawater,31,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Table 4.3,NaN,...,NaN,NaN,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992,1,"-18.8,70.983",0xE6100000010C098A1F63EEBE5140CDCCCCCCCCCC32C0,-18.800000,70.983333,521686
4,2032,2356,Greenland Sea,1,Seawater,31,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Table 4.3,NaN,...,NaN,NaN,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992,1,"-19.433,70.983",0xE6100000010C098A1F63EEBE5140575BB1BFEC6E33C0,-19.433333,70.983333,521687

In [ ]:
df.shape

(137, 79)

In [ ]:
#df = df.set_index('sample_id')
#df.index.name = 'sample'

In [ ]:
#df.head()

In [ ]:
cols = ['sample_id', 'areaname', 'latitude', 'longitude',
        'begperiod', 'totdepth', 'sampdepth', 'nusymbol', 
        'salinity', 'temperatur', 'counmet', 'detection',
        'activity', 'uncertaint', 'unit', 'profile']

In [ ]:
#df_sub = df[cols].sort_index()

In [ ]:
# This is a so-called `long` format
df_sub = df[cols]
df_sub

,sample_id,areaname,latitude,longitude,begperiod,totdepth,sampdepth,nusymbol,salinity,temperatur,counmet,detection,activity,uncertaint,unit,profile
0,2010,North Atlantic Ocean,65.683333,-24.383333,1988-09-07 00:00:00.000,NaN,5.0,90Sr,34.6,NaN,Beta,=,1.5800,NaN,Bq/m3,0.0
1,2045,North Atlantic Ocean,65.683333,-24.383333,1988-09-07 00:00:00.000,NaN,5.0,99Tc,34.6,NaN,Beta,=,0.0110,NaN,Bq/m3,0.0
2,2111,North Atlantic Ocean,65.683333,-24.383333,1988-09-07 00:00:00.000,NaN,5.0,137Cs,34.6,NaN,Gamma,=,2.8000,NaN,Bq/m3,0.0
3,2026,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,750.0,90Sr,34.9,0.3,Beta,=,1.8500,NaN,Bq/m3,0.0
4,2032,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,80.0,90Sr,34.2,1.5,Beta,=,3.1000,NaN,Bq/m3,0.0
5,2069,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,500.0,99Tc,34.9,1.0,Beta,=,0.0400,NaN,Bq/m3,0.0
6,2118,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,5.0,137Cs,32.8,1.9,Gamma,=,8.7000,NaN,Bq/m3,0.0
7,2012,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,5.0,90Sr,34.2,4.9,Beta,=,2.5000,NaN,Bq/m3,0.0
8,2018,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,86.0,90Sr,34.6,0.2,Beta,=,2.7000,NaN,Bq/m3,0.0
9,2135,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,500.0,137Cs,34.9,1.0,Gamma,=,6.5000,NaN,Bq/m3,0.0
10,2112,Greenland Sea,66.483333,-23.050000,1988-09-07 00:00:00.000,NaN,5.0,137Cs,34.5,NaN,Gamma,=,2.9000,NaN,Bq/m3,0.0
11,2141,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,80.0,137Cs,32.0,0.4,Gamma,=,8.2000,NaN,Bq/m3,0.0
12,2129,Greenland Sea,71.000000,-20.416667,1988-09-15 00:00:00.000,NaN,5.0,137Cs,31.5,0.5,Gamma,=,9.4000,NaN,Bq/m3,0.0
13,2081,Greenland Sea,67.133333,-22.900000,1988-09-25 00:00:00.000,NaN,100.0,99Tc,34.1,3.7,Beta,=,0.0460,NaN,Bq/m3,0.0
14,2095,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,500.0,134Cs,34.9,0.2,Gamma,=,0.3900,NaN,Bq/m3,0.0
15,2035,Greenland Sea,71.000000,-9.500000,1988-09-18 00:00:00.000,NaN,5.0,90Sr,34.5,NaN,Beta,=,2.3000,NaN,Bq/m3,0.0
16,2089,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,327.0,134Cs,34.9,0.9,Gamma,=,0.7000,NaN,Bq/m3,0.0
17,2052,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,5.0,99Tc,32.8,1.9,Beta,=,0.0790,NaN,Bq/m3,0.0
18,2121,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,803.0,137Cs,34.9,0.4,Gamma,=,3.9000,NaN,Bq/m3,0.0
19,2101,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,80.0,134Cs,34.2,1.5,Gamma,=,0.4100,NaN,Bq/m3,0.0
20,2078,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,150.0,99Tc,34.1,1.6,Beta,=,0.0290,NaN,Bq/m3,0.0
21,2029,Greenland Sea,71.000000,-20.416667,1988-09-15 00:00:00.000,NaN,80.0,90Sr,33.1,1.6,Beta,=,5.0000,NaN,Bq/m3,0.0
22,2058,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,80.0,99Tc,34.5,0.0,Beta,=,0.0670,NaN,Bq/m3,0.0
23,2072,Greenland Sea,70.000000,-17.933333,1988-09-19 00:00:00.000,NaN,5.0,99Tc,NaN,NaN,Beta,=,0.0590,NaN,Bq/m3,0.0
24,2015,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,535.0,90Sr,34.9,0.0,Beta,=,1.8900,NaN,Bq/m3,0.0
25,2066,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,5.0,99Tc,32.2,0.6,Beta,=,0.1060,NaN,Bq/m3,0.0
26,2115,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,327.0,137Cs,34.9,0.6,Gamma,=,5.6000,NaN,Bq/m3,0.0
27,2030,Greenland Sea,71.000000,-20.416667,1988-09-15 00:00:00.000,NaN,300.0,90Sr,34.8,0.6,Beta,=,2.0000,NaN,Bq/m3,0.0
28,2024,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,300.0,90Sr,34.9,1.0,Beta,=,2.1000,NaN,Bq/m3,0.0
29,2116,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,535.0,137Cs,34.9,0.0,Gamma,=,4.3000,NaN,Bq/m3,0.0
30,2067,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,80.0,99Tc,34.2,1.5,Beta,=,0.0860,NaN,Bq/m3,0.0
31,2087,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,5.0,134Cs,32.8,1.9,Gamma,=,0.4000,NaN,Bq/m3,0.0
32,2064,Greenland Sea,71.000000,-20.416667,1988-09-15 00:00:00.000,NaN,80.0,99Tc,33.1,1.6,Beta,=,0.0960,NaN,Bq/m3,0.0
33,2133,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,80.0,137Cs,34.2,1.5,Gamma,=,8.1000,NaN,Bq/m3,0.0
34,2110,Greenland Sea,67.133333,-22.900000,1988-09-25 00:00:00.000,NaN,100.0,134Cs,34.1,3.7,Gamma,=,0.2600,NaN,Bq/m3,0.0
35,2093,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,80.0,134Cs,34.5,0.0,Gamma,=,0.6600,NaN,Bq/m3,0.0
36,2033,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,500.0,90Sr,34.9,1.0,Beta,=,2.0000,NaN,Bq/m3,0.0
37,2047,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,5.0,99Tc,34.2,4.9,Beta,=,0.0450,NaN,Bq/m3,0.0
38,2041,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,500.0,90Sr,34.9,0.8,Beta,=,2.1000,NaN,Bq/m3,0.0
39,2027,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,1350.0,90Sr,34.9,0.8,Beta,=,2.0000,NaN,Bq/m3,0.0
40,2050,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,535.0,99Tc,34.9,0.0,Beta,=,0.0240,NaN,Bq/m3,0.0
41,2127,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,750.0,137Cs,34.9,0.3,Gamma,=,4.5000,NaN,Bq/m3,0.0
42,2021,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,1660.0,90Sr,34.9,0.8,Beta,=,0.8400,NaN,Bq/m3,0.0
43,2070,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,750.0,99Tc,34.9,0.3,Beta,=,0.0280,NaN,Bq/m3,0.0
44,2013,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,86.0,90Sr,34.6,0.4,Beta,=,2.4000,NaN,Bq/m3,0.0
45,2113,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,5.0,137Cs,34.2,4.9,Gamma,=,6.4000,NaN,Bq/m3,0.0
46,2088,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,86.0,134Cs,34.6,0.2,Gamma,=,0.6800,NaN,Bq/m3,0.0
47,2082,Greenland Sea,67.133333,-22.900000,1988-09-25 00:00:00.000,NaN,200.0,99Tc,34.8,1.8,Beta,=,0.0660,NaN,Bq/m3,0.0
48,2048,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,86.0,99Tc,34.6,0.4,Beta,=,0.0400,NaN,Bq/m3,0.0
49,2036,Greenland Sea,70.000000,-21.783333,1988-09-20 00:00:00.000,NaN,5.0,90Sr,28.8,NaN,Beta,=,4.0000,NaN,Bq/m3,0.0
50,2142,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,150.0,137Cs,34.1,1.6,Gamma,=,8.1000,NaN,Bq/m3,0.0
51,2042,Greenland Sea,67.133333,-22.900000,1988-09-25 00:00:00.000,NaN,5.0,90Sr,33.3,1.7,Beta,=,3.0000,NaN,Bq/m3,0.0
52,2028,Greenland Sea,71.000000,-20.416667,1988-09-15 00:00:00.000,NaN,5.0,90Sr,31.5,0.5,Beta,=,4.1000,NaN,Bq/m3,0.0
53,2145,Greenland Sea,67.133333,-22.900000,1988-09-25 00:00:00.000,NaN,100.0,137Cs,34.1,3.7,Gamma,=,6.5000,NaN,Bq/m3,0.0
54,2122,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,1660.0,137Cs,34.9,0.8,Gamma,=,2.3000,NaN,Bq/m3,0.0
55,2102,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,300.0,134Cs,NaN,1.3,Gamma,=,0.9000,NaN,Bq/m3,0.0
56,2043,Greenland Sea,67.133333,-22.900000,1988-09-25 00:00:00.000,NaN,100.0,90Sr,34.1,3.7,Beta,=,3.0000,NaN,Bq/m3,0.0
57,2037,Greenland Sea,68.650000,-26.333333,1988-09-24 00:00:00.000,NaN,5.0,90Sr,30.2,NaN,Beta,=,3.6000,NaN,Bq/m3,0.0
58,2143,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,500.0,137Cs,34.9,0.8,Gamma,=,5.8000,NaN,Bq/m3,0.0
59,2137,Greenland Sea,71.000000,-9.500000,1988-09-18 00:00:00.000,NaN,5.0,137Cs,34.5,NaN,Gamma,=,8.1000,NaN,Bq/m3,0.0
60,2123,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,5.0,137Cs,32.6,1.6,Gamma,=,8.8000,NaN,Bq/m3,0.0
61,2074,Greenland Sea,68.500000,-18.916667,1988-09-21 00:00:00.000,NaN,5.0,99Tc,NaN,NaN,Beta,=,0.0330,NaN,Bq/m3,0.0
62,2146,Greenland Sea,67.133333,-22.900000,1988-09-25 00:00:00.000,NaN,200.0,137Cs,34.8,1.8,Gamma,=,4.3000,NaN,Bq/m3,0.0
63,2097,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,1350.0,134Cs,34.9,0.8,Gamma,=,1.0100,NaN,Bq/m3,0.0
64,2031,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,5.0,90Sr,32.2,0.6,Beta,=,3.7000,NaN,Bq/m3,0.0
65,2080,Greenland Sea,67.133333,-22.900000,1988-09-25 00:00:00.000,NaN,5.0,99Tc,33.3,1.7,Beta,=,0.0920,NaN,Bq/m3,0.0
66,2054,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,327.0,99Tc,34.9,0.9,Beta,=,0.0450,NaN,Bq/m3,0.0
67,2103,Greenland Sea,71.000000,-9.500000,1988-09-18 00:00:00.000,NaN,5.0,134Cs,34.5,NaN,Gamma,=,0.5900,NaN,Bq/m3,0.0
68,2117,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,1017.0,137Cs,34.9,0.5,Gamma,=,2.5000,NaN,Bq/m3,0.0
69,2023,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,80.0,90Sr,34.5,0.0,Beta,=,2.6000,NaN,Bq/m3,0.0
70,2060,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,500.0,99Tc,34.9,0.2,Beta,=,0.0440,NaN,Bq/m3,0.0
71,2011,Greenland Sea,66.483333,-23.050000,1988-09-07 00:00:00.000,NaN,5.0,90Sr,34.5,NaN,Beta,=,1.6500,NaN,Bq/m3,0.0
72,2017,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,5.0,90Sr,32.8,1.9,Beta,=,3.4000,NaN,Bq/m3,0.0
73,2109,Greenland Sea,67.133333,-22.900000,1988-09-25 00:00:00.000,NaN,5.0,134Cs,33.3,1.7,Gamma,=,0.3800,NaN,Bq/m3,0.0
74,2132,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,5.0,137Cs,32.2,0.6,Gamma,=,9.1000,NaN,Bq/m3,0.0
75,2046,Greenland Sea,66.483333,-23.050000,1988-09-07 00:00:00.000,NaN,5.0,99Tc,34.5,NaN,Beta,=,0.0207,NaN,Bq/m3,0.0
76,2138,Greenland Sea,70.000000,-21.783333,1988-09-20 00:00:00.000,NaN,5.0,137Cs,28.8,NaN,Gamma,=,9.2000,NaN,Bq/m3,0.0
77,2038,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,5.0,90Sr,31.3,0.2,Beta,=,3.9000,NaN,Bq/m3,0.0
78,2092,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,5.0,134Cs,32.6,1.6,Gamma,=,0.4000,NaN,Bq/m3,0.0
79,2075,Greenland Sea,68.650000,-26.333333,1988-09-24 00:00:00.000,NaN,5.0,99Tc,30.2,NaN,Beta,=,0.0680,NaN,Bq/m3,0.0
80,2098,Greenland Sea,71.000000,-20.416667,1988-09-15 00:00:00.000,NaN,5.0,134Cs,31.5,0.5,Gamma,=,0.3300,NaN,Bq/m3,0.0
81,2055,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,803.0,99Tc,34.9,0.4,Beta,=,0.0360,NaN,Bq/m3,0.0
82,2049,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,327.0,99Tc,34.9,0.6,Beta,=,0.0420,NaN,Bq/m3,0.0
83,2108,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,150.0,134Cs,34.1,1.6,Gamma,=,0.4200,NaN,Bq/m3,0.0
84,2131,Greenland Sea,71.000000,-20.416667,1988-09-15 00:00:00.000,NaN,300.0,137Cs,34.8,0.6,Gamma,=,6.5000,NaN,Bq/m3,0.0
85,2039,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,80.0,90Sr,32.0,0.4,Beta,=,3.5000,NaN,Bq/m3,0.0
86,2016,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,1017.0,90Sr,34.9,0.5,Beta,=,1.3000,NaN,Bq/m3,0.0
87,2062,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,1350.0,99Tc,34.9,0.8,Beta,=,0.0560,NaN,Bq/m3,0.0
88,2085,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,86.0,134Cs,34.6,0.4,Gamma,=,0.5400,NaN,Bq/m3,0.0
89,2079,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,500.0,99Tc,34.9,0.8,Beta,=,0.0300,NaN,Bq/m3,0.0
90,2128,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,1350.0,137Cs,34.9,0.8,Gamma,=,6.5000,NaN,Bq/m3,0.0
91,2022,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,5.0,90Sr,32.6,1.6,Beta,=,3.4000,NaN,Bq/m3,0.0
92,2059,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,300.0,99Tc,34.9,1.0,Beta,=,0.0480,NaN,Bq/m3,0.0
93,2065,Greenland Sea,71.000000,-20.416667,1988-09-15 00:00:00.000,NaN,300.0,99Tc,34.8,0.6,Beta,=,0.0420,NaN,Bq/m3,0.0
94,2139,Greenland Sea,68.650000,-26.333333,1988-09-24 00:00:00.000,NaN,5.0,137Cs,30.2,NaN,Gamma,=,7.8000,NaN,Bq/m3,0.0
95,2091,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,1660.0,134Cs,34.9,0.8,Gamma,=,0.1400,NaN,Bq/m3,0.0
96,2099,Greenland Sea,71.000000,-20.416667,1988-09-15 00:00:00.000,NaN,300.0,134Cs,34.8,0.6,Gamma,=,0.7800,NaN,Bq/m3,0.0
97,2076,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,5.0,99Tc,31.3,0.2,Beta,=,0.0650,NaN,Bq/m3,0.0
98,2025,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,500.0,90Sr,34.9,0.2,Beta,=,2.0000,NaN,Bq/m3,0.0
99,2125,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,300.0,137Cs,34.9,1.0,Gamma,=,6.8000,NaN,Bq/m3,0.0
100,2056,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,1660.0,99Tc,34.9,0.8,Beta,=,0.0300,NaN,Bq/m3,0.0
101,2105,Greenland Sea,68.650000,-26.333333,1988-09-24 00:00:00.000,NaN,5.0,134Cs,30.2,NaN,Gamma,=,0.1400,NaN,Bq/m3,0.0
102,2019,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,327.0,90Sr,34.9,0.9,Beta,=,2.2000,NaN,Bq/m3,0.0
103,2119,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,86.0,137Cs,34.6,0.2,Gamma,=,7.4000,NaN,Bq/m3,0.0
104,2068,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,300.0,99Tc,NaN,1.3,Beta,=,0.0420,NaN,Bq/m3,0.0
105,2040,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,150.0,90Sr,34.1,1.6,Beta,=,3.3000,NaN,Bq/m3,0.0
106,2063,Greenland Sea,71.000000,-20.416667,1988-09-15 00:00:00.000,NaN,5.0,99Tc,31.5,0.5,Beta,=,0.1100,NaN,Bq/m3,0.0
107,2086,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,535.0,134Cs,34.9,0.0,Gamma,=,0.1600,NaN,Bq/m3,0.0
108,2134,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,300.0,137Cs,NaN,1.3,Gamma,=,7.0000,NaN,Bq/m3,0.0
109,2034,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,750.0,90Sr,34.9,0.3,Beta,=,1.3700,NaN,Bq/m3,0.0
110,2094,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,300.0,134Cs,34.9,1.0,Gamma,=,0.6400,NaN,Bq/m3,0.0
111,2140,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,5.0,137Cs,31.3,0.2,Gamma,=,8.4000,NaN,Bq/m3,0.0
112,2100,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,5.0,134Cs,32.2,0.6,Gamma,=,0.3800,NaN,Bq/m3,0.0
113,2051,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,1017.0,99Tc,34.9,0.5,Beta,=,0.0340,NaN,Bq/m3,0.0
114,2126,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,500.0,137Cs,34.9,0.2,Gamma,=,4.7000,NaN,Bq/m3,0.0
115,2077,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,80.0,99Tc,32.0,0.4,Beta,=,0.0780,NaN,Bq/m3,0.0
116,2106,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,5.0,134Cs,31.3,0.2,Gamma,=,0.2700,NaN,Bq/m3,0.0
117,2057,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,5.0,99Tc,32.6,1.6,Beta,=,0.0780,NaN,Bq/m3,0.0
118,2071,Greenland Sea,71.000000,-9.500000,1988-09-18 00:00:00.000,NaN,5.0,99Tc,34.5,NaN,Beta,=,0.0450,NaN,Bq/m3,0.0
119,2120,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,327.0,137Cs,34.9,0.9,Gamma,=,6.4000,NaN,Bq/m3,0.0
120,2114,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,86.0,137Cs,34.6,0.4,Gamma,=,7.1000,NaN,Bq/m3,0.0
121,2020,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,803.0,90Sr,34.9,0.4,Beta,=,1.6000,NaN,Bq/m3,0.0
122,2014,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,327.0,90Sr,34.9,0.6,Beta,=,1.9600,NaN,Bq/m3,0.0
123,2083,Greenland Sea,66.483333,-23.050000,1988-09-07 00:00:00.000,NaN,5.0,134Cs,34.5,NaN,Gamma,=,0.1400,NaN,Bq/m3,0.0
124,2084,Greenland Sea,70.983333,-14.333333,1988-09-11 00:00:00.000,NaN,5.0,134Cs,34.2,4.9,Gamma,=,0.5200,NaN,Bq/m3,0.0
125,2061,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,750.0,99Tc,34.9,0.3,Beta,=,0.0320,NaN,Bq/m3,0.0
126,2107,Greenland Sea,68.133333,-25.216667,1988-09-25 00:00:00.000,NaN,80.0,134Cs,32.0,0.4,Gamma,=,0.2400,NaN,Bq/m3,0.0
127,2130,Greenland Sea,71.000000,-20.416667,1988-09-15 00:00:00.000,NaN,80.0,137Cs,33.1,1.6,Gamma,=,10.1000,NaN,Bq/m3,0.0
128,2136,Greenland Sea,70.983333,-19.433333,1988-09-15 00:00:00.000,NaN,750.0,137Cs,34.9,0.3,Gamma,=,4.7000,NaN,Bq/m3,0.0
129,2090,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,803.0,134Cs,34.9,0.4,Gamma,=,0.4800,NaN,Bq/m3,0.0
130,2096,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,750.0,134Cs,34.9,0.3,Gamma,=,0.7000,NaN,Bq/m3,0.0
131,2144,Greenland Sea,67.133333,-22.900000,1988-09-25 00:00:00.000,NaN,5.0,137Cs,33.3,1.7,Gamma,=,7.4000,NaN,Bq/m3,0.0
132,2044,Greenland Sea,67.133333,-22.900000,1988-09-25 00:00:00.000,NaN,200.0,90Sr,34.8,1.8,Beta,=,1.9600,NaN,Bq/m3,0.0
133,2124,Greenland Sea,70.983333,-18.800000,1988-09-13 00:00:00.000,NaN,80.0,137Cs,34.5,0.0,Gamma,=,7.5000,NaN,Bq/m3,0.0
134,2073,Greenland Sea,70.000000,-21.783333,1988-09-20 00:00:00.000,NaN,5.0,99Tc,28.8,NaN,Beta,=,0.0780,NaN,Bq/m3,0.0
135,2053,Greenland Sea,71.000000,-17.283333,1988-09-12 00:00:00.000,NaN,86.0,99Tc,34.6,0.2,Beta,=,0.0740,NaN,Bq/m3,0.0
136,2104,Greenland Sea,70.000000,-21.783333,1988-09-20 00:00:00.000,NaN,5.0,134Cs,28.8,NaN,Gamma,=,0.3500,NaN,Bq/m3,0.0

In [ ]:
#df_sub.pivot(index='sample_id', columns='nusymbol', values=['activity', 'uncertaint', 'unit'])
df_nu = df[['sample_id', 'nusymbol', 'activity']].pivot(index='sample_id', columns='nusymbol', values=['activity'])
df_nu

          activity
nusymbol     134Cs 137Cs  90Sr    99Tc
sample_id
2010           NaN   NaN  1.58     NaN
2011           NaN   NaN  1.65     NaN
2012           NaN   NaN  2.50     NaN
2013           NaN   NaN  2.40     NaN
2014           NaN   NaN  1.96     NaN
2015           NaN   NaN  1.89     NaN
2016           NaN   NaN  1.30     NaN
2017           NaN   NaN  3.40     NaN
2018           NaN   NaN  2.70     NaN
2019           NaN   NaN  2.20     NaN
2020           NaN   NaN  1.60     NaN
2021           NaN   NaN  0.84     NaN
2022           NaN   NaN  3.40     NaN
2023           NaN   NaN  2.60     NaN
2024           NaN   NaN  2.10     NaN
2025           NaN   NaN  2.00     NaN
2026           NaN   NaN  1.85     NaN
2027           NaN   NaN  2.00     NaN
2028           NaN   NaN  4.10     NaN
2029           NaN   NaN  5.00     NaN
2030           NaN   NaN  2.00     NaN
2031           NaN   NaN  3.70     NaN
2032           NaN   NaN  3.10     NaN
2033           NaN   NaN  2.00     NaN
2034           NaN   NaN  1.37     NaN
2035           NaN   NaN  2.30     NaN
2036           NaN   NaN  4.00     NaN
2037           NaN   NaN  3.60     NaN
2038           NaN   NaN  3.90     NaN
2039           NaN   NaN  3.50     NaN
2040           NaN   NaN  3.30     NaN
2041           NaN   NaN  2.10     NaN
2042           NaN   NaN  3.00     NaN
2043           NaN   NaN  3.00     NaN
2044           NaN   NaN  1.96     NaN
2045           NaN   NaN   NaN  0.0110
2046           NaN   NaN   NaN  0.0207
2047           NaN   NaN   NaN  0.0450
2048           NaN   NaN   NaN  0.0400
2049           NaN   NaN   NaN  0.0420
2050           NaN   NaN   NaN  0.0240
2051           NaN   NaN   NaN  0.0340
2052           NaN   NaN   NaN  0.0790
2053           NaN   NaN   NaN  0.0740
2054           NaN   NaN   NaN  0.0450
2055           NaN   NaN   NaN  0.0360
2056           NaN   NaN   NaN  0.0300
2057           NaN   NaN   NaN  0.0780
2058           NaN   NaN   NaN  0.0670
2059           NaN   NaN   NaN  0.0480
2060           NaN   NaN   NaN  0.0440
2061           NaN   NaN   NaN  0.0320
2062           NaN   NaN   NaN  0.0560
2063           NaN   NaN   NaN  0.1100
2064           NaN   NaN   NaN  0.0960
2065           NaN   NaN   NaN  0.0420
2066           NaN   NaN   NaN  0.1060
2067           NaN   NaN   NaN  0.0860
2068           NaN   NaN   NaN  0.0420
2069           NaN   NaN   NaN  0.0400
2070           NaN   NaN   NaN  0.0280
2071           NaN   NaN   NaN  0.0450
2072           NaN   NaN   NaN  0.0590
2073           NaN   NaN   NaN  0.0780
2074           NaN   NaN   NaN  0.0330
2075           NaN   NaN   NaN  0.0680
2076           NaN   NaN   NaN  0.0650
2077           NaN   NaN   NaN  0.0780
2078           NaN   NaN   NaN  0.0290
2079           NaN   NaN   NaN  0.0300
2080           NaN   NaN   NaN  0.0920
2081           NaN   NaN   NaN  0.0460
2082           NaN   NaN   NaN  0.0660
2083          0.14   NaN   NaN     NaN
2084          0.52   NaN   NaN     NaN
2085          0.54   NaN   NaN     NaN
2086          0.16   NaN   NaN     NaN
2087          0.40   NaN   NaN     NaN
2088          0.68   NaN   NaN     NaN
2089          0.70   NaN   NaN     NaN
2090          0.48   NaN   NaN     NaN
2091          0.14   NaN   NaN     NaN
2092          0.40   NaN   NaN     NaN
2093          0.66   NaN   NaN     NaN
2094          0.64   NaN   NaN     NaN
2095          0.39   NaN   NaN     NaN
2096          0.70   NaN   NaN     NaN
2097          1.01   NaN   NaN     NaN
2098          0.33   NaN   NaN     NaN
2099          0.78   NaN   NaN     NaN
2100          0.38   NaN   NaN     NaN
2101          0.41   NaN   NaN     NaN
2102          0.90   NaN   NaN     NaN
2103          0.59   NaN   NaN     NaN
2104          0.35   NaN   NaN     NaN
2105          0.14   NaN   NaN     NaN
2106          0.27   NaN   NaN     NaN
2107          0.24   NaN   NaN     NaN
2108          0.42   NaN   NaN     NaN
2109          0.38   NaN   NaN     NaN
2110          0.26   NaN   NaN     NaN
2111           NaN   2.8   NaN     NaN
2112           NaN   2.9   NaN     NaN
2113           NaN   6.4   NaN     NaN
2114           NaN   7.1   NaN     NaN
2115           NaN   5.6   NaN     NaN
2116           NaN   4.3   NaN     NaN
2117           NaN   2.5   NaN     NaN
2118           NaN   8.7   NaN     NaN
2119           NaN   7.4   NaN     NaN
2120           NaN   6.4   NaN     NaN
2121           NaN   3.9   NaN     NaN
2122           NaN   2.3   NaN     NaN
2123           NaN   8.8   NaN     NaN
2124           NaN   7.5   NaN     NaN
2125           NaN   6.8   NaN     NaN
2126           NaN   4.7   NaN     NaN
2127           NaN   4.5   NaN     NaN
2128           NaN   6.5   NaN     NaN
2129           NaN   9.4   NaN     NaN
2130           NaN  10.1   NaN     NaN
2131           NaN   6.5   NaN     NaN
2132           NaN   9.1   NaN     NaN
2133           NaN   8.1   NaN     NaN
2134           NaN   7.0   NaN     NaN
2135           NaN   6.5   NaN     NaN
2136           NaN   4.7   NaN     NaN
2137           NaN   8.1   NaN     NaN
2138           NaN   9.2   NaN     NaN
2139           NaN   7.8   NaN     NaN
2140           NaN   8.4   NaN     NaN
2141           NaN   8.2   NaN     NaN
2142           NaN   8.1   NaN     NaN
2143           NaN   5.8   NaN     NaN
2144           NaN   7.4   NaN     NaN
2145           NaN   6.5   NaN     NaN
2146           NaN   4.3   NaN     NaN

In [ ]:
df_sub.pivot(index='sample_id', columns='nusymbol', values=['activity', 'uncertaint', 'unit'])

          activity                     uncertaint                   unit  \
nusymbol     134Cs 137Cs  90Sr    99Tc      134Cs 137Cs 90Sr 99Tc  134Cs
sample_id
2010           NaN   NaN  1.58     NaN        NaN   NaN  NaN  NaN    NaN
2011           NaN   NaN  1.65     NaN        NaN   NaN  NaN  NaN    NaN
2012           NaN   NaN   2.5     NaN        NaN   NaN  NaN  NaN    NaN
2013           NaN   NaN   2.4     NaN        NaN   NaN  NaN  NaN    NaN
2014           NaN   NaN  1.96     NaN        NaN   NaN  NaN  NaN    NaN
2015           NaN   NaN  1.89     NaN        NaN   NaN  NaN  NaN    NaN
2016           NaN   NaN   1.3     NaN        NaN   NaN  NaN  NaN    NaN
2017           NaN   NaN   3.4     NaN        NaN   NaN  NaN  NaN    NaN
2018           NaN   NaN   2.7     NaN        NaN   NaN  NaN  NaN    NaN
2019           NaN   NaN   2.2     NaN        NaN   NaN  NaN  NaN    NaN
2020           NaN   NaN   1.6     NaN        NaN   NaN  NaN  NaN    NaN
2021           NaN   NaN  0.84     NaN        NaN   NaN  NaN  NaN    NaN
2022           NaN   NaN   3.4     NaN        NaN   NaN  NaN  NaN    NaN
2023           NaN   NaN   2.6     NaN        NaN   NaN  NaN  NaN    NaN
2024           NaN   NaN   2.1     NaN        NaN   NaN  NaN  NaN    NaN
2025           NaN   NaN   2.0     NaN        NaN   NaN  NaN  NaN    NaN
2026           NaN   NaN  1.85     NaN        NaN   NaN  NaN  NaN    NaN
2027           NaN   NaN   2.0     NaN        NaN   NaN  NaN  NaN    NaN
2028           NaN   NaN   4.1     NaN        NaN   NaN  NaN  NaN    NaN
2029           NaN   NaN   5.0     NaN        NaN   NaN  NaN  NaN    NaN
2030           NaN   NaN   2.0     NaN        NaN   NaN  NaN  NaN    NaN
2031           NaN   NaN   3.7     NaN        NaN   NaN  NaN  NaN    NaN
2032           NaN   NaN   3.1     NaN        NaN   NaN  NaN  NaN    NaN
2033           NaN   NaN   2.0     NaN        NaN   NaN  NaN  NaN    NaN
2034           NaN   NaN  1.37     NaN        NaN   NaN  NaN  NaN    NaN
2035           NaN   NaN   2.3     NaN        NaN   NaN  NaN  NaN    NaN
2036           NaN   NaN   4.0     NaN        NaN   NaN  NaN  NaN    NaN
2037           NaN   NaN   3.6     NaN        NaN   NaN  NaN  NaN    NaN
2038           NaN   NaN   3.9     NaN        NaN   NaN  NaN  NaN    NaN
2039           NaN   NaN   3.5     NaN        NaN   NaN  NaN  NaN    NaN
2040           NaN   NaN   3.3     NaN        NaN   NaN  NaN  NaN    NaN
2041           NaN   NaN   2.1     NaN        NaN   NaN  NaN  NaN    NaN
2042           NaN   NaN   3.0     NaN        NaN   NaN  NaN  NaN    NaN
2043           NaN   NaN   3.0     NaN        NaN   NaN  NaN  NaN    NaN
2044           NaN   NaN  1.96     NaN        NaN   NaN  NaN  NaN    NaN
2045           NaN   NaN   NaN   0.011        NaN   NaN  NaN  NaN    NaN
2046           NaN   NaN   NaN  0.0207        NaN   NaN  NaN  NaN    NaN
2047           NaN   NaN   NaN   0.045        NaN   NaN  NaN  NaN    NaN
2048           NaN   NaN   NaN    0.04        NaN   NaN  NaN  NaN    NaN
2049           NaN   NaN   NaN   0.042        NaN   NaN  NaN  NaN    NaN
2050           NaN   NaN   NaN   0.024        NaN   NaN  NaN  NaN    NaN
2051           NaN   NaN   NaN   0.034        NaN   NaN  NaN  NaN    NaN
2052           NaN   NaN   NaN   0.079        NaN   NaN  NaN  NaN    NaN
2053           NaN   NaN   NaN   0.074        NaN   NaN  NaN  NaN    NaN
2054           NaN   NaN   NaN   0.045        NaN   NaN  NaN  NaN    NaN
2055           NaN   NaN   NaN   0.036        NaN   NaN  NaN  NaN    NaN
2056           NaN   NaN   NaN    0.03        NaN   NaN  NaN  NaN    NaN
2057           NaN   NaN   NaN   0.078        NaN   NaN  NaN  NaN    NaN
2058           NaN   NaN   NaN   0.067        NaN   NaN  NaN  NaN    NaN
2059           NaN   NaN   NaN   0.048        NaN   NaN  NaN  NaN    NaN
2060           NaN   NaN   NaN   0.044        NaN   NaN  NaN  NaN    NaN
2061           NaN   NaN   NaN   0.032        NaN   NaN  NaN  NaN    NaN
2062           NaN   NaN   NaN   0.056        NaN   NaN  NaN  NaN    NaN
2063           NaN   NaN   NaN    0.11        NaN   NaN  NaN  NaN    NaN
2064           NaN   NaN   NaN   0.096        NaN   NaN  NaN  NaN    NaN
2065           NaN   NaN   NaN   0.042        NaN   NaN  NaN  NaN    NaN
2066           NaN   NaN   NaN   0.106        NaN   NaN  NaN  NaN    NaN
2067           NaN   NaN   NaN   0.086        NaN   NaN  NaN  NaN    NaN
2068           NaN   NaN   NaN   0.042        NaN   NaN  NaN  NaN    NaN
2069           NaN   NaN   NaN    0.04        NaN   NaN  NaN  NaN    NaN
2070           NaN   NaN   NaN   0.028        NaN   NaN  NaN  NaN    NaN
2071           NaN   NaN   NaN   0.045        NaN   NaN  NaN  NaN    NaN
2072           NaN   NaN   NaN   0.059        NaN   NaN  NaN  NaN    NaN
2073           NaN   NaN   NaN   0.078        NaN   NaN  NaN  NaN    NaN
2074           NaN   NaN   NaN   0.033        NaN   NaN  NaN  NaN    NaN
2075           NaN   NaN   NaN   0.068        NaN   NaN  NaN  NaN    NaN
2076           NaN   NaN   NaN   0.065        NaN   NaN  NaN  NaN    NaN
2077           NaN   NaN   NaN   0.078        NaN   NaN  NaN  NaN    NaN
2078           NaN   NaN   NaN   0.029        NaN   NaN  NaN  NaN    NaN
2079           NaN   NaN   NaN    0.03        NaN   NaN  NaN  NaN    NaN
2080           NaN   NaN   NaN   0.092        NaN   NaN  NaN  NaN    NaN
2081           NaN   NaN   NaN   0.046        NaN   NaN  NaN  NaN    NaN
2082           NaN   NaN   NaN   0.066        NaN   NaN  NaN  NaN    NaN
2083          0.14   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2084          0.52   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2085          0.54   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2086          0.16   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2087           0.4   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2088          0.68   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2089           0.7   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2090          0.48   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2091          0.14   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2092           0.4   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2093          0.66   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2094          0.64   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2095          0.39   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2096           0.7   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2097          1.01   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2098          0.33   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2099          0.78   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2100          0.38   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2101          0.41   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2102           0.9   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2103          0.59   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2104          0.35   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2105          0.14   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2106          0.27   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2107          0.24   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2108          0.42   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2109          0.38   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2110          0.26   NaN   NaN     NaN        NaN   NaN  NaN  NaN  Bq/m3
2111           NaN   2.8   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2112           NaN   2.9   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2113           NaN   6.4   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2114           NaN   7.1   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2115           NaN   5.6   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2116           NaN   4.3   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2117           NaN   2.5   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2118           NaN   8.7   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2119           NaN   7.4   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2120           NaN   6.4   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2121           NaN   3.9   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2122           NaN   2.3   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2123           NaN   8.8   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2124           NaN   7.5   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2125           NaN   6.8   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2126           NaN   4.7   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2127           NaN   4.5   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2128           NaN   6.5   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2129           NaN   9.4   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2130           NaN  10.1   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2131           NaN   6.5   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2132           NaN   9.1   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2133           NaN   8.1   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2134           NaN   7.0   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2135           NaN   6.5   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2136           NaN   4.7   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2137           NaN   8.1   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2138           NaN   9.2   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2139           NaN   7.8   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2140           NaN   8.4   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2141           NaN   8.2   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2142           NaN   8.1   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2143           NaN   5.8   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2144           NaN   7.4   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2145           NaN   6.5   NaN     NaN        NaN   NaN  NaN  NaN    NaN
2146           NaN   4.3   NaN     NaN        NaN   NaN  NaN  NaN    NaN


nusymbol   137Cs   90Sr   99Tc
sample_id
2010         NaN  Bq/m3    NaN
2011         NaN  Bq/m3    NaN
2012         NaN  Bq/m3    NaN
2013         NaN  Bq/m3    NaN
2014         NaN  Bq/m3    NaN
2015         NaN  Bq/m3    NaN
2016         NaN  Bq/m3    NaN
2017         NaN  Bq/m3    NaN
2018         NaN  Bq/m3    NaN
2019         NaN  Bq/m3    NaN
2020         NaN  Bq/m3    NaN
2021         NaN  Bq/m3    NaN
2022         NaN  Bq/m3    NaN
2023         NaN  Bq/m3    NaN
2024         NaN  Bq/m3    NaN
2025         NaN  Bq/m3    NaN
2026         NaN  Bq/m3    NaN
2027         NaN  Bq/m3    NaN
2028         NaN  Bq/m3    NaN
2029         NaN  Bq/m3    NaN
2030         NaN  Bq/m3    NaN
2031         NaN  Bq/m3    NaN
2032         NaN  Bq/m3    NaN
2033         NaN  Bq/m3    NaN
2034         NaN  Bq/m3    NaN
2035         NaN  Bq/m3    NaN
2036         NaN  Bq/m3    NaN
2037         NaN  Bq/m3    NaN
2038         NaN  Bq/m3    NaN
2039         NaN  Bq/m3    NaN
2040         NaN  Bq/m3    NaN
2041         NaN  Bq/m3    NaN
2042         NaN  Bq/m3    NaN
2043         NaN  Bq/m3    NaN
2044         NaN  Bq/m3    NaN
2045         NaN    NaN  Bq/m3
2046         NaN    NaN  Bq/m3
2047         NaN    NaN  Bq/m3
2048         NaN    NaN  Bq/m3
2049         NaN    NaN  Bq/m3
2050         NaN    NaN  Bq/m3
2051         NaN    NaN  Bq/m3
2052         NaN    NaN  Bq/m3
2053         NaN    NaN  Bq/m3
2054         NaN    NaN  Bq/m3
2055         NaN    NaN  Bq/m3
2056         NaN    NaN  Bq/m3
2057         NaN    NaN  Bq/m3
2058         NaN    NaN  Bq/m3
2059         NaN    NaN  Bq/m3
2060         NaN    NaN  Bq/m3
2061         NaN    NaN  Bq/m3
2062         NaN    NaN  Bq/m3
2063         NaN    NaN  Bq/m3
2064         NaN    NaN  Bq/m3
2065         NaN    NaN  Bq/m3
2066         NaN    NaN  Bq/m3
2067         NaN    NaN  Bq/m3
2068         NaN    NaN  Bq/m3
2069         NaN    NaN  Bq/m3
2070         NaN    NaN  Bq/m3
2071         NaN    NaN  Bq/m3
2072         NaN    NaN  Bq/m3
2073         NaN    NaN  Bq/m3
2074         NaN    NaN  Bq/m3
2075         NaN    NaN  Bq/m3
2076         NaN    NaN  Bq/m3
2077         NaN    NaN  Bq/m3
2078         NaN    NaN  Bq/m3
2079         NaN    NaN  Bq/m3
2080         NaN    NaN  Bq/m3
2081         NaN    NaN  Bq/m3
2082         NaN    NaN  Bq/m3
2083         NaN    NaN    NaN
2084         NaN    NaN    NaN
2085         NaN    NaN    NaN
2086         NaN    NaN    NaN
2087         NaN    NaN    NaN
2088         NaN    NaN    NaN
2089         NaN    NaN    NaN
2090         NaN    NaN    NaN
2091         NaN    NaN    NaN
2092         NaN    NaN    NaN
2093         NaN    NaN    NaN
2094         NaN    NaN    NaN
2095         NaN    NaN    NaN
2096         NaN    NaN    NaN
2097         NaN    NaN    NaN
2098         NaN    NaN    NaN
2099         NaN    NaN    NaN
2100         NaN    NaN    NaN
2101         NaN    NaN    NaN
2102         NaN    NaN    NaN
2103         NaN    NaN    NaN
2104         NaN    NaN    NaN
2105         NaN    NaN    NaN
2106         NaN    NaN    NaN
2107         NaN    NaN    NaN
2108         NaN    NaN    NaN
2109         NaN    NaN    NaN
2110         NaN    NaN    NaN
2111       Bq/m3    NaN    NaN
2112       Bq/m3    NaN    NaN
2113       Bq/m3    NaN    NaN
2114       Bq/m3    NaN    NaN
2115       Bq/m3    NaN    NaN
2116       Bq/m3    NaN    NaN
2117       Bq/m3    NaN    NaN
2118       Bq/m3    NaN    NaN
2119       Bq/m3    NaN    NaN
2120       Bq/m3    NaN    NaN
2121       Bq/m3    NaN    NaN
2122       Bq/m3    NaN    NaN
2123       Bq/m3    NaN    NaN
2124       Bq/m3    NaN    NaN
2125       Bq/m3    NaN    NaN
2126       Bq/m3    NaN    NaN
2127       Bq/m3    NaN    NaN
2128       Bq/m3    NaN    NaN
2129       Bq/m3    NaN    NaN
2130       Bq/m3    NaN    NaN
2131       Bq/m3    NaN    NaN
2132       Bq/m3    NaN    NaN
2133       Bq/m3    NaN    NaN
2134       Bq/m3    NaN    NaN
2135       Bq/m3    NaN    NaN
2136       Bq/m3    NaN    NaN
2137       Bq/m3    NaN    NaN
2138       Bq/m3    NaN    NaN
2139       Bq/m3    NaN    NaN
2140       Bq/m3    NaN    NaN
2141       Bq/m3    NaN    NaN
2142       Bq/m3    NaN    NaN
2143       Bq/m3    NaN    NaN
2144       Bq/m3    NaN    NaN
2145       Bq/m3    NaN    NaN
2146       Bq/m3    NaN    NaN

In [ ]:
df_nu.index.name

'sample_id'

In [ ]:
df_nu.columns

MultiIndex([('activity', '134Cs'),
            ('activity', '137Cs'),
            ('activity',  '90Sr'),
            ('activity',  '99Tc')],
           names=[None, 'nusymbol'])

In [ ]:
df_nu.columns = [nu for _, nu in df_nu.columns]

In [ ]:
df_nu

           134Cs  137Cs  90Sr    99Tc
sample_id
2010         NaN    NaN  1.58     NaN
2011         NaN    NaN  1.65     NaN
2012         NaN    NaN  2.50     NaN
2013         NaN    NaN  2.40     NaN
2014         NaN    NaN  1.96     NaN
2015         NaN    NaN  1.89     NaN
2016         NaN    NaN  1.30     NaN
2017         NaN    NaN  3.40     NaN
2018         NaN    NaN  2.70     NaN
2019         NaN    NaN  2.20     NaN
2020         NaN    NaN  1.60     NaN
2021         NaN    NaN  0.84     NaN
2022         NaN    NaN  3.40     NaN
2023         NaN    NaN  2.60     NaN
2024         NaN    NaN  2.10     NaN
2025         NaN    NaN  2.00     NaN
2026         NaN    NaN  1.85     NaN
2027         NaN    NaN  2.00     NaN
2028         NaN    NaN  4.10     NaN
2029         NaN    NaN  5.00     NaN
2030         NaN    NaN  2.00     NaN
2031         NaN    NaN  3.70     NaN
2032         NaN    NaN  3.10     NaN
2033         NaN    NaN  2.00     NaN
2034         NaN    NaN  1.37     NaN
2035         NaN    NaN  2.30     NaN
2036         NaN    NaN  4.00     NaN
2037         NaN    NaN  3.60     NaN
2038         NaN    NaN  3.90     NaN
2039         NaN    NaN  3.50     NaN
2040         NaN    NaN  3.30     NaN
2041         NaN    NaN  2.10     NaN
2042         NaN    NaN  3.00     NaN
2043         NaN    NaN  3.00     NaN
2044         NaN    NaN  1.96     NaN
2045         NaN    NaN   NaN  0.0110
2046         NaN    NaN   NaN  0.0207
2047         NaN    NaN   NaN  0.0450
2048         NaN    NaN   NaN  0.0400
2049         NaN    NaN   NaN  0.0420
2050         NaN    NaN   NaN  0.0240
2051         NaN    NaN   NaN  0.0340
2052         NaN    NaN   NaN  0.0790
2053         NaN    NaN   NaN  0.0740
2054         NaN    NaN   NaN  0.0450
2055         NaN    NaN   NaN  0.0360
2056         NaN    NaN   NaN  0.0300
2057         NaN    NaN   NaN  0.0780
2058         NaN    NaN   NaN  0.0670
2059         NaN    NaN   NaN  0.0480
2060         NaN    NaN   NaN  0.0440
2061         NaN    NaN   NaN  0.0320
2062         NaN    NaN   NaN  0.0560
2063         NaN    NaN   NaN  0.1100
2064         NaN    NaN   NaN  0.0960
2065         NaN    NaN   NaN  0.0420
2066         NaN    NaN   NaN  0.1060
2067         NaN    NaN   NaN  0.0860
2068         NaN    NaN   NaN  0.0420
2069         NaN    NaN   NaN  0.0400
2070         NaN    NaN   NaN  0.0280
2071         NaN    NaN   NaN  0.0450
2072         NaN    NaN   NaN  0.0590
2073         NaN    NaN   NaN  0.0780
2074         NaN    NaN   NaN  0.0330
2075         NaN    NaN   NaN  0.0680
2076         NaN    NaN   NaN  0.0650
2077         NaN    NaN   NaN  0.0780
2078         NaN    NaN   NaN  0.0290
2079         NaN    NaN   NaN  0.0300
2080         NaN    NaN   NaN  0.0920
2081         NaN    NaN   NaN  0.0460
2082         NaN    NaN   NaN  0.0660
2083        0.14    NaN   NaN     NaN
2084        0.52    NaN   NaN     NaN
2085        0.54    NaN   NaN     NaN
2086        0.16    NaN   NaN     NaN
2087        0.40    NaN   NaN     NaN
2088        0.68    NaN   NaN     NaN
2089        0.70    NaN   NaN     NaN
2090        0.48    NaN   NaN     NaN
2091        0.14    NaN   NaN     NaN
2092        0.40    NaN   NaN     NaN
2093        0.66    NaN   NaN     NaN
2094        0.64    NaN   NaN     NaN
2095        0.39    NaN   NaN     NaN
2096        0.70    NaN   NaN     NaN
2097        1.01    NaN   NaN     NaN
2098        0.33    NaN   NaN     NaN
2099        0.78    NaN   NaN     NaN
2100        0.38    NaN   NaN     NaN
2101        0.41    NaN   NaN     NaN
2102        0.90    NaN   NaN     NaN
2103        0.59    NaN   NaN     NaN
2104        0.35    NaN   NaN     NaN
2105        0.14    NaN   NaN     NaN
2106        0.27    NaN   NaN     NaN
2107        0.24    NaN   NaN     NaN
2108        0.42    NaN   NaN     NaN
2109        0.38    NaN   NaN     NaN
2110        0.26    NaN   NaN     NaN
2111         NaN    2.8   NaN     NaN
2112         NaN    2.9   NaN     NaN
2113         NaN    6.4   NaN     NaN
2114         NaN    7.1   NaN     NaN
2115         NaN    5.6   NaN     NaN
2116         NaN    4.3   NaN     NaN
2117         NaN    2.5   NaN     NaN
2118         NaN    8.7   NaN     NaN
2119         NaN    7.4   NaN     NaN
2120         NaN    6.4   NaN     NaN
2121         NaN    3.9   NaN     NaN
2122         NaN    2.3   NaN     NaN
2123         NaN    8.8   NaN     NaN
2124         NaN    7.5   NaN     NaN
2125         NaN    6.8   NaN     NaN
2126         NaN    4.7   NaN     NaN
2127         NaN    4.5   NaN     NaN
2128         NaN    6.5   NaN     NaN
2129         NaN    9.4   NaN     NaN
2130         NaN   10.1   NaN     NaN
2131         NaN    6.5   NaN     NaN
2132         NaN    9.1   NaN     NaN
2133         NaN    8.1   NaN     NaN
2134         NaN    7.0   NaN     NaN
2135         NaN    6.5   NaN     NaN
2136         NaN    4.7   NaN     NaN
2137         NaN    8.1   NaN     NaN
2138         NaN    9.2   NaN     NaN
2139         NaN    7.8   NaN     NaN
2140         NaN    8.4   NaN     NaN
2141         NaN    8.2   NaN     NaN
2142         NaN    8.1   NaN     NaN
2143         NaN    5.8   NaN     NaN
2144         NaN    7.4   NaN     NaN
2145         NaN    6.5   NaN     NaN
2146         NaN    4.3   NaN     NaN

In [ ]:
df[['activity', 'temperatur', 'nusymbol', 'nuclide_id', 'salinity',
    'areaname', 'latitude', 'longitude', 'sampdepth', 'totdepth']]

,activity,temperatur,nusymbol,nuclide_id,salinity,areaname,latitude,longitude,sampdepth,totdepth
0,1.5800,NaN,90Sr,12,34.6,North Atlantic Ocean,65.683333,-24.383333,5.0,NaN
1,0.0110,NaN,99Tc,15,34.6,North Atlantic Ocean,65.683333,-24.383333,5.0,NaN
2,2.8000,NaN,137Cs,33,34.6,North Atlantic Ocean,65.683333,-24.383333,5.0,NaN
3,1.8500,0.3,90Sr,12,34.9,Greenland Sea,70.983333,-18.800000,750.0,NaN
4,3.1000,1.5,90Sr,12,34.2,Greenland Sea,70.983333,-19.433333,80.0,NaN
5,0.0400,1.0,99Tc,15,34.9,Greenland Sea,70.983333,-19.433333,500.0,NaN
6,8.7000,1.9,137Cs,33,32.8,Greenland Sea,71.000000,-17.283333,5.0,NaN
7,2.5000,4.9,90Sr,12,34.2,Greenland Sea,70.983333,-14.333333,5.0,NaN
8,2.7000,0.2,90Sr,12,34.6,Greenland Sea,71.000000,-17.283333,86.0,NaN
9,6.5000,1.0,137Cs,33,34.9,Greenland Sea,70.983333,-19.433333,500.0,NaN
10,2.9000,NaN,137Cs,33,34.5,Greenland Sea,66.483333,-23.050000,5.0,NaN
11,8.2000,0.4,137Cs,33,32.0,Greenland Sea,68.133333,-25.216667,80.0,NaN
12,9.4000,0.5,137Cs,33,31.5,Greenland Sea,71.000000,-20.416667,5.0,NaN
13,0.0460,3.7,99Tc,15,34.1,Greenland Sea,67.133333,-22.900000,100.0,NaN
14,0.3900,0.2,134Cs,31,34.9,Greenland Sea,70.983333,-18.800000,500.0,NaN
15,2.3000,NaN,90Sr,12,34.5,Greenland Sea,71.000000,-9.500000,5.0,NaN
16,0.7000,0.9,134Cs,31,34.9,Greenland Sea,71.000000,-17.283333,327.0,NaN
17,0.0790,1.9,99Tc,15,32.8,Greenland Sea,71.000000,-17.283333,5.0,NaN
18,3.9000,0.4,137Cs,33,34.9,Greenland Sea,71.000000,-17.283333,803.0,NaN
19,0.4100,1.5,134Cs,31,34.2,Greenland Sea,70.983333,-19.433333,80.0,NaN
20,0.0290,1.6,99Tc,15,34.1,Greenland Sea,68.133333,-25.216667,150.0,NaN
21,5.0000,1.6,90Sr,12,33.1,Greenland Sea,71.000000,-20.416667,80.0,NaN
22,0.0670,0.0,99Tc,15,34.5,Greenland Sea,70.983333,-18.800000,80.0,NaN
23,0.0590,NaN,99Tc,15,NaN,Greenland Sea,70.000000,-17.933333,5.0,NaN
24,1.8900,0.0,90Sr,12,34.9,Greenland Sea,70.983333,-14.333333,535.0,NaN
25,0.1060,0.6,99Tc,15,32.2,Greenland Sea,70.983333,-19.433333,5.0,NaN
26,5.6000,0.6,137Cs,33,34.9,Greenland Sea,70.983333,-14.333333,327.0,NaN
27,2.0000,0.6,90Sr,12,34.8,Greenland Sea,71.000000,-20.416667,300.0,NaN
28,2.1000,1.0,90Sr,12,34.9,Greenland Sea,70.983333,-18.800000,300.0,NaN
29,4.3000,0.0,137Cs,33,34.9,Greenland Sea,70.983333,-14.333333,535.0,NaN
30,0.0860,1.5,99Tc,15,34.2,Greenland Sea,70.983333,-19.433333,80.0,NaN
31,0.4000,1.9,134Cs,31,32.8,Greenland Sea,71.000000,-17.283333,5.0,NaN
32,0.0960,1.6,99Tc,15,33.1,Greenland Sea,71.000000,-20.416667,80.0,NaN
33,8.1000,1.5,137Cs,33,34.2,Greenland Sea,70.983333,-19.433333,80.0,NaN
34,0.2600,3.7,134Cs,31,34.1,Greenland Sea,67.133333,-22.900000,100.0,NaN
35,0.6600,0.0,134Cs,31,34.5,Greenland Sea,70.983333,-18.800000,80.0,NaN
36,2.0000,1.0,90Sr,12,34.9,Greenland Sea,70.983333,-19.433333,500.0,NaN
37,0.0450,4.9,99Tc,15,34.2,Greenland Sea,70.983333,-14.333333,5.0,NaN
38,2.1000,0.8,90Sr,12,34.9,Greenland Sea,68.133333,-25.216667,500.0,NaN
39,2.0000,0.8,90Sr,12,34.9,Greenland Sea,70.983333,-18.800000,1350.0,NaN
40,0.0240,0.0,99Tc,15,34.9,Greenland Sea,70.983333,-14.333333,535.0,NaN
41,4.5000,0.3,137Cs,33,34.9,Greenland Sea,70.983333,-18.800000,750.0,NaN
42,0.8400,0.8,90Sr,12,34.9,Greenland Sea,71.000000,-17.283333,1660.0,NaN
43,0.0280,0.3,99Tc,15,34.9,Greenland Sea,70.983333,-19.433333,750.0,NaN
44,2.4000,0.4,90Sr,12,34.6,Greenland Sea,70.983333,-14.333333,86.0,NaN
45,6.4000,4.9,137Cs,33,34.2,Greenland Sea,70.983333,-14.333333,5.0,NaN
46,0.6800,0.2,134Cs,31,34.6,Greenland Sea,71.000000,-17.283333,86.0,NaN
47,0.0660,1.8,99Tc,15,34.8,Greenland Sea,67.133333,-22.900000,200.0,NaN
48,0.0400,0.4,99Tc,15,34.6,Greenland Sea,70.983333,-14.333333,86.0,NaN
49,4.0000,NaN,90Sr,12,28.8,Greenland Sea,70.000000,-21.783333,5.0,NaN
50,8.1000,1.6,137Cs,33,34.1,Greenland Sea,68.133333,-25.216667,150.0,NaN
51,3.0000,1.7,90Sr,12,33.3,Greenland Sea,67.133333,-22.900000,5.0,NaN
52,4.1000,0.5,90Sr,12,31.5,Greenland Sea,71.000000,-20.416667,5.0,NaN
53,6.5000,3.7,137Cs,33,34.1,Greenland Sea,67.133333,-22.900000,100.0,NaN
54,2.3000,0.8,137Cs,33,34.9,Greenland Sea,71.000000,-17.283333,1660.0,NaN
55,0.9000,1.3,134Cs,31,NaN,Greenland Sea,70.983333,-19.433333,300.0,NaN
56,3.0000,3.7,90Sr,12,34.1,Greenland Sea,67.133333,-22.900000,100.0,NaN
57,3.6000,NaN,90Sr,12,30.2,Greenland Sea,68.650000,-26.333333,5.0,NaN
58,5.8000,0.8,137Cs,33,34.9,Greenland Sea,68.133333,-25.216667,500.0,NaN
59,8.1000,NaN,137Cs,33,34.5,Greenland Sea,71.000000,-9.500000,5.0,NaN
60,8.8000,1.6,137Cs,33,32.6,Greenland Sea,70.983333,-18.800000,5.0,NaN
61,0.0330,NaN,99Tc,15,NaN,Greenland Sea,68.500000,-18.916667,5.0,NaN
62,4.3000,1.8,137Cs,33,34.8,Greenland Sea,67.133333,-22.900000,200.0,NaN
63,1.0100,0.8,134Cs,31,34.9,Greenland Sea,70.983333,-18.800000,1350.0,NaN
64,3.7000,0.6,90Sr,12,32.2,Greenland Sea,70.983333,-19.433333,5.0,NaN
65,0.0920,1.7,99Tc,15,33.3,Greenland Sea,67.133333,-22.900000,5.0,NaN
66,0.0450,0.9,99Tc,15,34.9,Greenland Sea,71.000000,-17.283333,327.0,NaN
67,0.5900,NaN,134Cs,31,34.5,Greenland Sea,71.000000,-9.500000,5.0,NaN
68,2.5000,0.5,137Cs,33,34.9,Greenland Sea,70.983333,-14.333333,1017.0,NaN
69,2.6000,0.0,90Sr,12,34.5,Greenland Sea,70.983333,-18.800000,80.0,NaN
70,0.0440,0.2,99Tc,15,34.9,Greenland Sea,70.983333,-18.800000,500.0,NaN
71,1.6500,NaN,90Sr,12,34.5,Greenland Sea,66.483333,-23.050000,5.0,NaN
72,3.4000,1.9,90Sr,12,32.8,Greenland Sea,71.000000,-17.283333,5.0,NaN
73,0.3800,1.7,134Cs,31,33.3,Greenland Sea,67.133333,-22.900000,5.0,NaN
74,9.1000,0.6,137Cs,33,32.2,Greenland Sea,70.983333,-19.433333,5.0,NaN
75,0.0207,NaN,99Tc,15,34.5,Greenland Sea,66.483333,-23.050000,5.0,NaN
76,9.2000,NaN,137Cs,33,28.8,Greenland Sea,70.000000,-21.783333,5.0,NaN
77,3.9000,0.2,90Sr,12,31.3,Greenland Sea,68.133333,-25.216667,5.0,NaN
78,0.4000,1.6,134Cs,31,32.6,Greenland Sea,70.983333,-18.800000,5.0,NaN
79,0.0680,NaN,99Tc,15,30.2,Greenland Sea,68.650000,-26.333333,5.0,NaN
80,0.3300,0.5,134Cs,31,31.5,Greenland Sea,71.000000,-20.416667,5.0,NaN
81,0.0360,0.4,99Tc,15,34.9,Greenland Sea,71.000000,-17.283333,803.0,NaN
82,0.0420,0.6,99Tc,15,34.9,Greenland Sea,70.983333,-14.333333,327.0,NaN
83,0.4200,1.6,134Cs,31,34.1,Greenland Sea,68.133333,-25.216667,150.0,NaN
84,6.5000,0.6,137Cs,33,34.8,Greenland Sea,71.000000,-20.416667,300.0,NaN
85,3.5000,0.4,90Sr,12,32.0,Greenland Sea,68.133333,-25.216667,80.0,NaN
86,1.3000,0.5,90Sr,12,34.9,Greenland Sea,70.983333,-14.333333,1017.0,NaN
87,0.0560,0.8,99Tc,15,34.9,Greenland Sea,70.983333,-18.800000,1350.0,NaN
88,0.5400,0.4,134Cs,31,34.6,Greenland Sea,70.983333,-14.333333,86.0,NaN
89,0.0300,0.8,99Tc,15,34.9,Greenland Sea,68.133333,-25.216667,500.0,NaN
90,6.5000,0.8,137Cs,33,34.9,Greenland Sea,70.983333,-18.800000,1350.0,NaN
91,3.4000,1.6,90Sr,12,32.6,Greenland Sea,70.983333,-18.800000,5.0,NaN
92,0.0480,1.0,99Tc,15,34.9,Greenland Sea,70.983333,-18.800000,300.0,NaN
93,0.0420,0.6,99Tc,15,34.8,Greenland Sea,71.000000,-20.416667,300.0,NaN
94,7.8000,NaN,137Cs,33,30.2,Greenland Sea,68.650000,-26.333333,5.0,NaN
95,0.1400,0.8,134Cs,31,34.9,Greenland Sea,71.000000,-17.283333,1660.0,NaN
96,0.7800,0.6,134Cs,31,34.8,Greenland Sea,71.000000,-20.416667,300.0,NaN
97,0.0650,0.2,99Tc,15,31.3,Greenland Sea,68.133333,-25.216667,5.0,NaN
98,2.0000,0.2,90Sr,12,34.9,Greenland Sea,70.983333,-18.800000,500.0,NaN
99,6.8000,1.0,137Cs,33,34.9,Greenland Sea,70.983333,-18.800000,300.0,NaN
100,0.0300,0.8,99Tc,15,34.9,Greenland Sea,71.000000,-17.283333,1660.0,NaN
101,0.1400,NaN,134Cs,31,30.2,Greenland Sea,68.650000,-26.333333,5.0,NaN
102,2.2000,0.9,90Sr,12,34.9,Greenland Sea,71.000000,-17.283333,327.0,NaN
103,7.4000,0.2,137Cs,33,34.6,Greenland Sea,71.000000,-17.283333,86.0,NaN
104,0.0420,1.3,99Tc,15,NaN,Greenland Sea,70.983333,-19.433333,300.0,NaN
105,3.3000,1.6,90Sr,12,34.1,Greenland Sea,68.133333,-25.216667,150.0,NaN
106,0.1100,0.5,99Tc,15,31.5,Greenland Sea,71.000000,-20.416667,5.0,NaN
107,0.1600,0.0,134Cs,31,34.9,Greenland Sea,70.983333,-14.333333,535.0,NaN
108,7.0000,1.3,137Cs,33,NaN,Greenland Sea,70.983333,-19.433333,300.0,NaN
109,1.3700,0.3,90Sr,12,34.9,Greenland Sea,70.983333,-19.433333,750.0,NaN
110,0.6400,1.0,134Cs,31,34.9,Greenland Sea,70.983333,-18.800000,300.0,NaN
111,8.4000,0.2,137Cs,33,31.3,Greenland Sea,68.133333,-25.216667,5.0,NaN
112,0.3800,0.6,134Cs,31,32.2,Greenland Sea,70.983333,-19.433333,5.0,NaN
113,0.0340,0.5,99Tc,15,34.9,Greenland Sea,70.983333,-14.333333,1017.0,NaN
114,4.7000,0.2,137Cs,33,34.9,Greenland Sea,70.983333,-18.800000,500.0,NaN
115,0.0780,0.4,99Tc,15,32.0,Greenland Sea,68.133333,-25.216667,80.0,NaN
116,0.2700,0.2,134Cs,31,31.3,Greenland Sea,68.133333,-25.216667,5.0,NaN
117,0.0780,1.6,99Tc,15,32.6,Greenland Sea,70.983333,-18.800000,5.0,NaN
118,0.0450,NaN,99Tc,15,34.5,Greenland Sea,71.000000,-9.500000,5.0,NaN
119,6.4000,0.9,137Cs,33,34.9,Greenland Sea,71.000000,-17.283333,327.0,NaN
120,7.1000,0.4,137Cs,33,34.6,Greenland Sea,70.983333,-14.333333,86.0,NaN
121,1.6000,0.4,90Sr,12,34.9,Greenland Sea,71.000000,-17.283333,803.0,NaN
122,1.9600,0.6,90Sr,12,34.9,Greenland Sea,70.983333,-14.333333,327.0,NaN
123,0.1400,NaN,134Cs,31,34.5,Greenland Sea,66.483333,-23.050000,5.0,NaN
124,0.5200,4.9,134Cs,31,34.2,Greenland Sea,70.983333,-14.333333,5.0,NaN
125,0.0320,0.3,99Tc,15,34.9,Greenland Sea,70.983333,-18.800000,750.0,NaN
126,0.2400,0.4,134Cs,31,32.0,Greenland Sea,68.133333,-25.216667,80.0,NaN
127,10.1000,1.6,137Cs,33,33.1,Greenland Sea,71.000000,-20.416667,80.0,NaN
128,4.7000,0.3,137Cs,33,34.9,Greenland Sea,70.983333,-19.433333,750.0,NaN
129,0.4800,0.4,134Cs,31,34.9,Greenland Sea,71.000000,-17.283333,803.0,NaN
130,0.7000,0.3,134Cs,31,34.9,Greenland Sea,70.983333,-18.800000,750.0,NaN
131,7.4000,1.7,137Cs,33,33.3,Greenland Sea,67.133333,-22.900000,5.0,NaN
132,1.9600,1.8,90Sr,12,34.8,Greenland Sea,67.133333,-22.900000,200.0,NaN
133,7.5000,0.0,137Cs,33,34.5,Greenland Sea,70.983333,-18.800000,80.0,NaN
134,0.0780,NaN,99Tc,15,28.8,Greenland Sea,70.000000,-21.783333,5.0,NaN
135,0.0740,0.2,99Tc,15,34.6,Greenland Sea,71.000000,-17.283333,86.0,NaN
136,0.3500,NaN,134Cs,31,28.8,Greenland Sea,70.000000,-21.783333,5.0,NaN

In [ ]:
df.ref_fulltext[0]

'Aarkrog, A., Buch, E., Chen, Q.J., Christensen, G.C., Dahlgaard, H., Hansen, H., Holm, E., Nielsen, S.P., 1992. Environmental radioactivity in the North Atlantic Region including the Faroe Islands and Greenland. 1988 and 1989 (No. RisÃ¸-R-571).'

In [ ]:
attr_global = ['samptype', 'displaytext', 'zoterourl', 'lab', 'ref_fulltext', 'ref_yearpub']

In [ ]:
df[attr_global]

,samptype,displaytext,zoterourl,lab,ref_fulltext,ref_yearpub
0,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
1,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
2,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
3,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
4,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
5,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
6,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
7,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
8,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
9,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
10,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
11,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
12,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
13,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
14,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
15,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
16,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
17,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
18,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
19,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
20,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
21,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
22,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
23,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
24,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
25,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
26,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
27,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
28,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
29,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
30,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
31,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
32,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
33,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
34,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
35,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
36,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
37,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
38,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
39,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
40,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
41,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
42,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
43,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
44,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
45,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
46,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
47,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
48,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
49,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
50,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
51,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
52,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
53,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
54,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
55,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
56,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
57,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
58,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
59,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
60,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
61,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
62,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
63,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
64,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
65,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
66,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
67,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
68,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
69,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
70,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
71,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
72,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
73,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
74,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
75,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
76,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
77,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
78,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
79,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
80,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
81,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
82,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
83,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
84,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
85,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
86,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
87,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
88,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
89,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
90,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
91,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
92,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
93,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
94,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
95,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
96,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
97,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
98,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
99,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
100,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
101,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992
102,Seawater,"Aarkrog et al., 1992",https://www.zotero.org/groups/2432820/maris/it...,Harvard University - Harvard University Center...,"Aarkrog, A., Buch, E., Chen, Q.J., Christensen...",1992

In [ ]:
df.columns

Index(['sample_id', 'area_id', 'areaname', 'samptype_id', 'samptype', 'ref_id',
       'displaytext', 'zoterourl', 'ref_note', 'datbase', 'lab_id', 'lab',
       'latitude', 'longitude', 'begperiod', 'endperiod', 'samplingyear',
       'totdepth', 'sampdepth', 'station', 'samplabcode', 'species_id',
       'taxonname', 'taxonrank', 'biogroup', 'taxondb', 'taxondbid',
       'taxondburl', 'taxonrepname', 'bodypar_id', 'bodypar', 'sliceup',
       'slicedown', 'sedtype_id', 'sedtype', 'sedrepname', 'nuclide_id',
       'nusymbol', 'volume', 'salinity', 'temperatur', 'filtered', 'filtpore',
       'samparea', 'drywt', 'wetwt', 'percentwt', 'sampmet_id', 'sampmet',
       'prepmet_id', 'prepmet', 'drymet_id', 'drymet', 'counmet_id', 'counmet',
       'decayedto', 'detection', 'activity', 'uncertaint', 'unit_id', 'unit',
       'vartype', 'freq', 'rangelow', 'rangeupp', 'profile', 'transect_id',
       'measure_note', 'shapetype_id', 'profile_id', 'sampnote',
       'ref_fulltext', 'ref_yearpub', 'ref_sampleTypes', 'LongLat',
       'displaycoordinates', 'DisplayLong', 'DisplayLat', 'id'],
      dtype='object')

In [ ]:
df.apply(lambda x: x.unique())

sample_id             [2010, 2045, 2111, 2026, 2032, 2069, 2118, 201...
area_id                                                    [1912, 2356]
areaname                          [North Atlantic Ocean, Greenland Sea]
samptype_id                                                         [1]
samptype                                                     [Seawater]
ref_id                                                             [31]
displaytext                                      [Aarkrog et al., 1992]
zoterourl             [https://www.zotero.org/groups/2432820/maris/i...
ref_note                                                    [Table 4.3]
datbase                                                           [nan]
lab_id                                                             [70]
lab                   [Harvard University - Harvard University Cente...
latitude              [65.6833333333333, 70.9833333333333, 71.0, 66....
longitude             [-24.3833333333333, -18.8, -19.4333333333333, ...
begperiod             [1988-09-07 00:00:00.000, 1988-09-13 00:00:00....
endperiod                                                         [nan]
samplingyear                                                     [1988]
totdepth                                                          [nan]
sampdepth             [5.0, 750.0, 80.0, 500.0, 86.0, 100.0, 327.0, ...
station                                                           [nan]
samplabcode                                                       [nan]
species_id                                                          [0]
taxonname                                             [(Not available)]
taxonrank                                                         [nan]
biogroup                                              [(Not available)]
taxondb                                                           [nan]
taxondbid                                                         [nan]
taxondburl                                                        [nan]
taxonrepname                                                      [nan]
bodypar_id                                                          [0]
bodypar                                               [(Not available)]
sliceup                                                           [nan]
slicedown                                                         [nan]
sedtype_id                                                          [0]
sedtype                                               [(Not available)]
sedrepname                                                        [nan]
nuclide_id                                             [12, 15, 33, 31]
nusymbol                                     [90Sr, 99Tc, 137Cs, 134Cs]
volume                                                            [nan]
salinity              [34.6, 34.9, 34.2, 32.8, 34.5, 32.0, 31.5, 34....
temperatur            [nan, 0.3, 1.5, 1.0, 1.9, 4.9, 0.2, 0.4, 0.5, ...
filtered                                                          [nan]
filtpore                                                          [nan]
samparea                                                          [nan]
drywt                                                             [nan]
wetwt                                                             [nan]
percentwt                                                         [nan]
sampmet_id                                                          [0]
sampmet                                                 [Not available]
prepmet_id                                                          [0]
prepmet                                                 [Not available]
drymet_id                                                           [0]
drymet                                                  [Not available]
counmet_id                                                      [8, 18]
counmet                                                   [Beta, Gamma]
decayedto                                                         [nan]
detection                                                           [=]
activity              [1.58, 0.011, 2.8, 1.85, 3.1, 0.04, 8.7, 2.5, ...
uncertaint                                                        [nan]
unit_id                                                             [1]
unit                                                            [Bq/m3]
vartype                                                           [nan]
freq                                                              [nan]
rangelow                                                          [nan]
rangeupp                                                          [nan]
profile                                                           [0.0]
transect_id                                                       [nan]
measure_note                                                      [nan]
shapetype_id                                                        [1]
profile_id                                                        [nan]
sampnote                                                          [nan]
ref_fulltext          [Aarkrog, A., Buch, E., Chen, Q.J., Christense...
ref_yearpub                                                      [1992]
ref_sampleTypes                                                     [1]
LongLat               [-24.383,65.683, -18.8,70.983, -19.433,70.983,...
displaycoordinates    [0xE6100000010CD656EC2FBB6B50408A8EE4F21F6238C...
DisplayLong           [-24.3833333333333, -18.8, -19.4333333333333, ...
DisplayLat            [65.6833333333333, 70.9833333333333, 71.0, 66....
id                    [461829, 461830, 461831, 521686, 521687, 52168...
dtype: object

In [ ]:
# Which cols are global attributes candidate?
df.apply(lambda x: len(x.unique())).sort_values(ascending=False)

sample_id             137
id                    137
activity              105
temperatur             18
salinity               17
sampdepth              15
longitude              14
DisplayLong            14
displaycoordinates     14
LongLat                14
begperiod              11
DisplayLat              9
latitude                9
nusymbol                4
nuclide_id              4
counmet                 2
area_id                 2
counmet_id              2
areaname                2
detection               1
decayedto               1
samptype                1
drymet_id               1
drymet                  1
unit_id                 1
prepmet                 1
prepmet_id              1
sampmet                 1
uncertaint              1
rangelow                1
unit                    1
vartype                 1
freq                    1
percentwt               1
rangeupp                1
profile                 1
transect_id             1
measure_note            1
shapetype_id            1
profile_id              1
sampnote                1
ref_fulltext            1
ref_yearpub             1
ref_sampleTypes         1
sampmet_id              1
ref_id                  1
wetwt                   1
taxondb                 1
zoterourl               1
ref_note                1
datbase                 1
lab_id                  1
lab                     1
endperiod               1
samplingyear            1
totdepth                1
station                 1
samplabcode             1
species_id              1
taxonname               1
taxonrank               1
biogroup                1
taxondbid               1
drywt                   1
taxondburl              1
taxonrepname            1
bodypar_id              1
bodypar                 1
sliceup                 1
slicedown               1
sedtype_id              1
sedtype                 1
sedrepname              1
volume                  1
samptype_id             1
filtered                1
displaytext             1
samparea                1
filtpore                1
dtype: int64

In [ ]:
rootgrp = Dataset("test.nc", "a")

In [ ]:
# Global attribute
rootgrp.description = "bogus example script"
rootgrp.history = "Created " + time.ctime(time.time())
rootgrp.source = "netCDF4 python module tutorial"

In [ ]:
# The `sample` unlimited dimension
sample_dim = rootgrp.createDimension("sample", None)

In [ ]:
rootgrp

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    description: bogus example script
    history: Created Tue Oct 11 14:54:51 2022
    source: netCDF4 python module tutorial
    dimensions(sizes): sample(0)
    variables(dimensions):
    groups:

In [ ]:
df.columns

Index(['sample_id', 'area_id', 'areaname', 'samptype_id', 'samptype', 'ref_id',
       'displaytext', 'zoterourl', 'ref_note', 'datbase', 'lab_id', 'lab',
       'latitude', 'longitude', 'begperiod', 'endperiod', 'samplingyear',
       'totdepth', 'sampdepth', 'station', 'samplabcode', 'species_id',
       'taxonname', 'taxonrank', 'biogroup', 'taxondb', 'taxondbid',
       'taxondburl', 'taxonrepname', 'bodypar_id', 'bodypar', 'sliceup',
       'slicedown', 'sedtype_id', 'sedtype', 'sedrepname', 'nuclide_id',
       'nusymbol', 'volume', 'salinity', 'temperatur', 'filtered', 'filtpore',
       'samparea', 'drywt', 'wetwt', 'percentwt', 'sampmet_id', 'sampmet',
       'prepmet_id', 'prepmet', 'drymet_id', 'drymet', 'counmet_id', 'counmet',
       'decayedto', 'detection', 'activity', 'uncertaint', 'unit_id', 'unit',
       'vartype', 'freq', 'rangelow', 'rangeupp', 'profile', 'transect_id',
       'measure_note', 'shapetype_id', 'profile_id', 'sampnote',
       'ref_fulltext', 'ref_yearpub', 'ref_sampleTypes', 'LongLat',
       'displaycoordinates', 'DisplayLong', 'DisplayLat', 'id'],
      dtype='object')

In [ ]:
df['station']

0        T-0
1        T-0
2        T-0
3        T-0
4        T-0
        ...
99097    T-6
99098    T-6
99099    T-6
99100    T-6
99101    T-6
Name: station, Length: 99102, dtype: object

In [ ]:
df.columns

Index(['sample_id', 'area_id', 'areaname', 'samptype_id', 'samptype', 'ref_id',
       'displaytext', 'zoterourl', 'ref_note', 'datbase', 'lab_id', 'lab',
       'latitude', 'longitude', 'begperiod', 'endperiod', 'samplingyear',
       'totdepth', 'sampdepth', 'station', 'samplabcode', 'species_id',
       'taxonname', 'taxonrank', 'biogroup', 'taxondb', 'taxondbid',
       'taxondburl', 'taxonrepname', 'bodypar_id', 'bodypar', 'sliceup',
       'slicedown', 'sedtype_id', 'sedtype', 'sedrepname', 'nuclide_id',
       'nusymbol', 'volume', 'salinity', 'temperatur', 'filtered', 'filtpore',
       'samparea', 'drywt', 'wetwt', 'percentwt', 'sampmet_id', 'sampmet',
       'prepmet_id', 'prepmet', 'drymet_id', 'drymet', 'counmet_id', 'counmet',
       'decayedto', 'detection', 'activity', 'uncertaint', 'unit_id', 'unit',
       'vartype', 'freq', 'rangelow', 'rangeupp', 'profile', 'transect_id',
       'measure_note', 'shapetype_id', 'profile_id', 'sampnote',
       'ref_fulltext', 'ref_yearpub', 'ref_sampleTypes', 'LongLat',
       'displaycoordinates', 'DisplayLong', 'DisplayLat', 'id'],
      dtype='object')

In [ ]:
df.describe()

,sample_id,area_id,samptype_id,ref_id,ref_note,lab_id,latitude,longitude,endperiod,samplingyear,...,rangeupp,profile,transect_id,shapetype_id,profile_id,ref_yearpub,ref_sampleTypes,DisplayLong,DisplayLat,id
count,99102.000000,99102.000000,99102.0,99102.0,0.0,99102.0,99102.000000,99102.000000,0.0,99102.000000,...,0.0,99102.0,0.0,99102.0,24343.000000,99102.0,99102.0,99102.000000,99102.000000,99102.000000
mean,515851.610391,3816.082188,1.0,121.0,NaN,0.0,37.412011,141.057938,NaN,2014.296230,...,NaN,0.0,NaN,1.0,121.547333,2011.0,1.0,141.057938,37.412011,350148.125729
std,9045.379826,3434.768463,0.0,0.0,NaN,0.0,0.312317,0.117420,NaN,1.878099,...,NaN,0.0,NaN,0.0,0.258886,0.0,0.0,0.117420,0.312317,263991.202340
min,499882.000000,1908.000000,1.0,121.0,NaN,0.0,35.796111,140.603889,NaN,2011.000000,...,NaN,0.0,NaN,1.0,121.103310,2011.0,1.0,140.603889,35.796111,15439.000000
25%,507960.250000,1908.000000,1.0,121.0,NaN,0.0,37.406111,141.034444,NaN,2013.000000,...,NaN,0.0,NaN,1.0,121.274045,2011.0,1.0,141.034444,37.406111,136614.250000
50%,515673.000000,1908.000000,1.0,121.0,NaN,0.0,37.423333,141.041389,NaN,2015.000000,...,NaN,0.0,NaN,1.0,121.700020,2011.0,1.0,141.041389,37.423333,276786.500000
75%,523642.750000,1908.000000,1.0,121.0,NaN,0.0,37.423333,141.046667,NaN,2016.000000,...,NaN,0.0,NaN,1.0,121.787220,2011.0,1.0,141.046667,37.423333,424641.750000
max,532690.000000,9999.000000,1.0,121.0,NaN,0.0,38.633333,141.666667,NaN,2017.000000,...,NaN,0.0,NaN,1.0,121.941400,2011.0,1.0,141.666667,38.633333,795265.000000

In [ ]:
df['nusymbol'].unique()

array(['90Sr', '99Tc', '137Cs', '134Cs'], dtype=object)

In [ ]:
for col, n in df.apply(lambda col: len(col.unique())).iteritems():
    if n < 3:
        print(f'{col}: {df[col].unique()}')

area_id: [1912 2356]
areaname: ['North Atlantic Ocean' 'Greenland Sea']
samptype_id: [1]
samptype: ['Seawater']
ref_id: [31]
displaytext: ['Aarkrog et al., 1992']
zoterourl: ['https://www.zotero.org/groups/2432820/maris/items/CRYJ794W']
ref_note: ['Table 4.3']
datbase: [nan]
lab_id: [70]
lab: ['Harvard University - Harvard University Center for the Environment']
endperiod: [nan]
samplingyear: [1988]
totdepth: [nan]
station: [nan]
samplabcode: [nan]
species_id: [0]
taxonname: ['(Not available)']
taxonrank: [nan]
biogroup: ['(Not available)']
taxondb: [nan]
taxondbid: [nan]
taxondburl: [nan]
taxonrepname: [nan]
bodypar_id: [0]
bodypar: ['(Not available)']
sliceup: [nan]
slicedown: [nan]
sedtype_id: [0]
sedtype: ['(Not available)']
sedrepname: [nan]
volume: [nan]
filtered: [nan]
filtpore: [nan]
samparea: [nan]
drywt: [nan]
wetwt: [nan]
percentwt: [nan]
sampmet_id: [0]
sampmet: ['Not available']
prepmet_id: [0]
prepmet: ['Not available']
drymet_id: [0]
drymet: ['Not available']
counmet_id: [ 8 18]
counmet: ['Beta' 'Gamma']
decayedto: [nan]
detection: ['=']
uncertaint: [nan]
unit_id: [1]
unit: ['Bq/m3']
vartype: [nan]
freq: [nan]
rangelow: [nan]
rangeupp: [nan]
profile: [0.]
transect_id: [nan]
measure_note: [nan]
shapetype_id: [1]
profile_id: [nan]
sampnote: [nan]
ref_fulltext: ['Aarkrog, A., Buch, E., Chen, Q.J., Christensen, G.C., Dahlgaard, H., Hansen, H., Holm, E., Nielsen, S.P., 1992. Environmental radioactivity in the North Atlantic Region including the Faroe Islands and Greenland. 1988 and 1989 (No. RisÃ¸-R-571).']
ref_yearpub: [1992]
ref_sampleTypes: [1]

In [ ]:
df['id']

0         15439
1         15440
2         15441
3         15442
4         15443
          ...
99097    795261
99098    795262
99099    795263
99100    795264
99101    795265
Name: id, Length: 99102, dtype: int64

In [ ]:
df['nusymbol'].unique()

array(['T-BETA', '134Cs', '137Cs', '131I', '3H', '90Sr', 'T-ALPHA',
       '89Sr', '238Pu', '239,240Pu', '144Ce', '54Mn', '60Co', '136Cs',
       '140La', '125Sb', '132I', '58Co', '140Ba', '106Ru', '105Ru',
       '132Te', '95Zr', '129Te', '99Mo', '99mTc', '129mTe', '135I'],
      dtype=object)

In [ ]:
df['profile_id'].unique()

array([      nan, 121.60896, 121.60897, ..., 121.75815, 121.75833,
       121.75834])

In [ ]:
df_sub = df[['longitude', 'latitude', 'begperiod', 
             'sampdepth', 'totdepth', 'station', 
             'nusymbol', 'activity', 'uncertaint', 'profile_id']]


df_sub = df[['latitude', 'longitude', 'begperiod',
             'sampdepth',
             'nusymbol', 'activity', 'uncertaint']]
df_sub['begperiod'] = pd.to_datetime(df_sub['begperiod'])
df_sub

,latitude,longitude,begperiod,sampdepth,nusymbol,activity,uncertaint
0,37.423333,141.041389,2015-04-14 17:00:00,2.0,T-BETA,8700.0,NaN
1,37.423333,141.041389,2015-04-14 17:00:00,2.0,134Cs,120.0,NaN
2,37.423333,141.041389,2015-04-14 17:00:00,2.0,137Cs,540.0,NaN
3,37.423333,141.041389,2015-06-15 20:00:00,2.0,T-BETA,8700.0,NaN
4,37.423333,141.041389,2015-06-15 20:00:00,2.0,134Cs,120.0,NaN
...,...,...,...,...,...,...,...
99097,37.478889,141.040556,2017-08-15 09:50:00,3.0,137Cs,10.0,NaN
99098,37.478889,141.040556,2017-08-22 09:40:00,3.0,134Cs,2.1,NaN
99099,37.478889,141.040556,2017-08-22 09:40:00,3.0,137Cs,19.0,NaN
99100,37.478889,141.040556,2017-08-29 09:40:00,3.0,134Cs,6.5,NaN
99101,37.478889,141.040556,2017-08-29 09:40:00,3.0,137Cs,39.0,NaN

In [ ]:
df_pivoted = pd.pivot_table(df_sub, values=['activity', 'uncertaint'], 
                            index=['latitude', 'longitude', 'sampdepth', 'begperiod'],
                            columns=['nusymbol'])

df_pivoted.sort_values(by=['begperiod', 'sampdepth'], inplace=True)
df_pivoted.reset_index(inplace=True)
#df_pivoted.columns = flatten_cols(df_pivoted.columns)
df_pivoted

           latitude   longitude sampdepth           begperiod activity        \
nusymbol                                                         105Ru 106Ru
0         37.415278  141.033889       2.0 2011-03-21 14:30:00      NaN   NaN
1         37.322222  141.026389       3.0 2011-03-21 23:15:00      NaN   NaN
2         37.241667  141.013889       3.0 2011-03-21 23:45:00      NaN   NaN
3         37.338889  141.028056       3.0 2011-03-22 00:38:00      NaN   NaN
4         37.415278  141.033889       2.0 2011-03-22 06:30:00      NaN   NaN
...             ...         ...       ...                 ...      ...   ...
32690     37.431111  141.034444       2.0 2017-09-28 07:39:00      NaN   NaN
32691     37.406111  141.033611       2.0 2017-09-29 06:55:00      NaN   NaN
32692     37.415278  141.033889       2.0 2017-09-29 06:55:00      NaN   NaN
32693     37.423333  141.041389       2.0 2017-09-29 07:02:00      NaN   NaN
32694     37.431111  141.034444       2.0 2017-09-29 08:25:00      NaN   NaN

                                        ...                                    \
nusymbol 125Sb 129Te 129mTe       131I  ...     58Co 60Co 89Sr 90Sr 95Zr 99Mo
0          NaN   NaN    NaN  5100000.0  ...  60000.0  NaN  NaN  NaN  NaN  NaN
1          NaN   NaN    NaN  1100000.0  ...   5700.0  NaN  NaN  NaN  NaN  NaN
2          NaN   NaN    NaN   660000.0  ...   6800.0  NaN  NaN  NaN  NaN  NaN
3          NaN   NaN    NaN  3200000.0  ...  10000.0  NaN  NaN  NaN  NaN  NaN
4          NaN   NaN    NaN  1200000.0  ...  17000.0  NaN  NaN  NaN  NaN  NaN
...        ...   ...    ...        ...  ...      ...  ...  ...  ...  ...  ...
32690      NaN   NaN    NaN      740.0  ...      NaN  NaN  NaN  NaN  NaN  NaN
32691      NaN   NaN    NaN      700.0  ...      NaN  NaN  NaN  NaN  NaN  NaN
32692      NaN   NaN    NaN      700.0  ...      NaN  NaN  NaN  NaN  NaN  NaN
32693      NaN   NaN    NaN        NaN  ...      NaN  NaN  NaN  NaN  NaN  NaN
32694      NaN   NaN    NaN      670.0  ...      NaN  NaN  NaN  NaN  NaN  NaN

                                uncertaint
nusymbol 99mTc T-ALPHA   T-BETA  239,240Pu
0          NaN     NaN      NaN        NaN
1          NaN     NaN      NaN        NaN
2          NaN     NaN      NaN        NaN
3          NaN     NaN      NaN        NaN
4          NaN     NaN      NaN        NaN
...        ...     ...      ...        ...
32690      NaN     NaN      NaN        NaN
32691      NaN     NaN  11000.0        NaN
32692      NaN     NaN      NaN        NaN
32693      NaN     NaN  17000.0        NaN
32694      NaN     NaN      NaN        NaN

[32695 rows x 33 columns]

In [ ]:
df_pivoted.columns

MultiIndex([(  'latitude',          ''),
            ( 'longitude',          ''),
            ( 'sampdepth',          ''),
            ( 'begperiod',          ''),
            (  'activity',     '105Ru'),
            (  'activity',     '106Ru'),
            (  'activity',     '125Sb'),
            (  'activity',     '129Te'),
            (  'activity',    '129mTe'),
            (  'activity',      '131I'),
            (  'activity',      '132I'),
            (  'activity',     '132Te'),
            (  'activity',     '134Cs'),
            (  'activity',      '135I'),
            (  'activity',     '136Cs'),
            (  'activity',     '137Cs'),
            (  'activity',     '140Ba'),
            (  'activity',     '140La'),
            (  'activity',     '144Ce'),
            (  'activity',     '238Pu'),
            (  'activity', '239,240Pu'),
            (  'activity',        '3H'),
            (  'activity',      '54Mn'),
            (  'activity',      '58Co'),
            (  'activity',      '60Co'),
            (  'activity',      '89Sr'),
            (  'activity',      '90Sr'),
            (  'activity',      '95Zr'),
            (  'activity',      '99Mo'),
            (  'activity',     '99mTc'),
            (  'activity',   'T-ALPHA'),
            (  'activity',    'T-BETA'),
            ('uncertaint', '239,240Pu')],
           names=[None, 'nusymbol'])

In [ ]:
#pd.pivot_table(df_sub, values=['activity'], 
#               index=['longitude', 'latitude', 'begperiod', 
#                      'sampdepth', 'totdepth', 'station', 'profile_id'],
#               columns=['nusymbol']).reset_index()

## Questions

- Is the attribute a function of the measure or dataset?
- variable names?
- variable attributes such as long_name, ... (unit we have)

## Ideal API

In [ ]:
options: {
   ...
}
    
netcdf = NetCDFier(path)

marisco.read_netcdf()
marisco.csv_to_netcdf()

netcdf.from_csv(path, configs)
netcdf.to_csv()

In [ ]:
class NetCDF:
    def __init__(self):
        pass
    def __call__(self, ...):
        pass

In [ ]:
from marisco import csv_to_netcdf

dest_dir = ''
for file in paths:
    netcdf = csv_to_netcdf(file, cfg)

netcdf.plot()
netcdf.summary()

In [ ]:
CONFIGS = {
    'vars': {
        '131I': {
            'colname': '131I',
            'long_name': 'Iodine 131',
            'unit': 'Bq/kg'
        },
        '134Cs': {
            'colname': '134Cs',
            'long_name': 'Cesium 134',
            'unit': 'Bq/kg'
        }}
}; CONFIG

{'vars': {'131I': {'colname': '131I',
   'long_name': 'Iodine 131',
   'unit': 'Bq/kg'},
  '134Cs': {'colname': '134Cs', 'long_name': 'Cesium 134', 'unit': 'Bq/kg'}}}

In [ ]:
CONFIGS['vars']['131I']

{'colname': '131I', 'long_name': 'Iodine 131', 'unit': 'Bq/kg'}

In [ ]:
ds_attrs = {
    'name': "IFREMER"